from typing import Protocol, Any, Optional, List, TypeVar, Union

T = TypeVar("T")

class DatabaseSessionProtocol(Protocol):
    """Protocol for database session operations required by AuthCore."""
    def add(self, instance: Any) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def delete(self, instance: Any) -> None: ...
    def close(self) -> None: ...
    def query(self, *entities: Any) -> Any: ...
    def execute(self, statement: Any, params: Optional[Any] = None) -> Any: ...

class EmailServiceProtocol(Protocol):
    """Protocol for sending emails."""
    def send_email(self, to_email: str, subject: str, body_html: str) -> bool: ...

class ConfigProviderProtocol(Protocol):
    """Protocol for retrieving configuration values."""
    def get(self, key: str, default: Any = None) -> Any: ...
